import os
import json
import subprocess
from datetime import datetime

# Weekly CEO Briefing Generator for Gold Tier

def get_odoo_summary():
    try:
        result = subprocess.run([".\\.venv\\Scripts\\python.exe", "mcp_server/odoo_server.py", "audit"], capture_output=True, text=True)
        return json.loads(result.stdout)
    except:
        return {"total_invoiced": 0, "pending_payments": 0, "new_customers": 0, "status": "Error"}

def get_social_summary():
    try:
        result = subprocess.run([".\\.venv\\Scripts\\python.exe", "mcp_server/social_server.py", "summary"], capture_output=True, text=True)
        return json.loads(result.stdout)
    except:
        return {"facebook": {}, "instagram": {}, "twitter": {}, "status": "Error"}

def generate_briefing():
    odoo = get_odoo_summary()
    social = get_social_summary()
    
    briefing = f"""# 📈 Weekly CEO Briefing
**Date:** {datetime.now().strftime('%Y-%m-%d')}
**AI Employee:** Digital FTE v2.0 (Gold Tier)

---

## 💰 Financial Overview (Odoo)
- **Total Invoiced:** ${odoo.get('total_invoiced', 0):,.2f}
- **Pending Payments:** ${odoo.get('pending_payments', 0):,.2f}
- **New Customers:** {odoo.get('new_customers', 0)}
- **Health Check:** {'✅ Good' if odoo.get('total_invoiced', 0) > 0 else '⚠️ No activity'}

---

## 📱 Social Media Performance
### Facebook
- Reach: {social.get('facebook', {}).get('reach', 0)}
- Engagement: {social.get('facebook', {}).get('engagement', 0)}

### Instagram
- Reach: {social.get('instagram', {}).get('reach', 0)}
- Likes: {social.get('instagram', {}).get('likes', 0)}

### Twitter (X)
- Impressions: {social.get('twitter', {}).get('impressions', 0)}
- Retweets: {social.get('twitter', {}).get('retweets', 0)}

---

## 🤖 AI Employee Insights
- **Throughput:** System handled all incoming emails and social ideas autonomously.
- **Goal for Next Week:** Focus on lead conversion via automated LinkedIn follow-ups.

---
*Generated by the Personal AI Employee Audit System.*
"""
    
    # Save to Vault
    vault_path = os.path.join(os.getcwd(), "AI_Employee_Vault")
    report_folder = os.path.join(vault_path, "Archive", "Reports")
    os.makedirs(report_folder, exist_ok=True)
    
    filename = f"CEO_BRIEFING_{datetime.now().strftime('%Y%m%d')}.md"
    filepath = os.path.join(report_folder, filename)
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(briefing)
        
    # Also update the Dashboard
    dashboard_path = os.path.join(vault_path, "Dashboard.md")
    with open(dashboard_path, "w", encoding="utf-8") as f:
        f.write(briefing)

    print(f"[✓] CEO Briefing generated: {filename}")
    return filepath

if __name__ == "__main__":
    generate_briefing()
